# Test Request
GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Settings
POST {{baseUrl}}/settings HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "instagram_username": "test_username3",
    "instagram_password": "test_password3"
}

### Get Settings
GET {{baseUrl}}/settings HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json