# Test Request
GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Settings
POST {{baseUrl}}/settings HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "instagram_username": "test_username3",
    "instagram_password": "test_password3"
}

### Get Settings
GET {{baseUrl}}/settings HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Upload an image
POST {{baseUrl}}/assets HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{}

### Get Assets
GET {{baseUrl}}/assets HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{}

### Delete Assets
DELETE {{baseUrl}}/assets/091676eb-b0ea-4e54-a44a-24f2224bed06 HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{}

### Get Content
GET {{baseUrl}}/content/648ebcac-0a4a-48ec-abd5-350ed839540d HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{}