# Test Request
GET {{baseUrl}} HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

### Create Settings
POST {{baseUrl}}/settings HTTP/1.1
Authorization: Bearer {{token}}
content-type: application/json

{
    "instagram_username": "test_username2",
    "instagram_password": "test_password2"
}