"""add_encryption_key_column_and_increase_character_limit_in_settings

Revision ID: ab9341aadbe2
Revises: 01967a8d9607
Create Date: 2023-08-20 11:07:20.697587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ab9341aadbe2"
down_revision: Union[str, None] = "01967a8d9607"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("settings", sa.Column("encryption_key", sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "encryption_key")
    # ### end Alembic commands ###
