"""remove_unique_id_in_assets_table

Revision ID: e34ae5d53326
Revises: f4079f56f4a9
Create Date: 2023-08-27 20:57:01.405298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e34ae5d53326'
down_revision: Union[str, None] = 'f4079f56f4a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_assets_user_id', table_name='assets')
    op.create_index(op.f('ix_assets_user_id'), 'assets', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_assets_user_id'), table_name='assets')
    op.create_index('ix_assets_user_id', 'assets', ['user_id'], unique=False)
    # ### end Alembic commands ###
