"""remove_stored_filename_in_assets_table

Revision ID: f4079f56f4a9
Revises: 1fbdcfdba247
Create Date: 2023-08-27 20:35:08.384461

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4079f56f4a9'
down_revision: Union[str, None] = '1fbdcfdba247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'assets', ['id'])
    op.drop_column('assets', 'stored_filename')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('stored_filename', sa.VARCHAR(length=1000), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='unique')
    # ### end Alembic commands ###
